apiVersion: apps/v1
kind: Deployment
metadata:
  name: citas
  labels:
    app: citas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citas
  template:
    metadata:
      labels:
        app: citas
    spec:
      containers:
      - name: citas
        image: gcr.io/mario-214921/citas_v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: s-citas
spec:
  type: ClusterIP
  selector:
    app: citas
  ports:
    - name: citas
      protocol: TCP
      port: 3002
      targetPort: 3002